name: "Nuget: publish"

on:
  workflow_dispatch:
  push:
    paths:
      - "WebAppTemplates.csproj"
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Setup dotnet 9
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0
      
      # Run the publishing action
      - name: Pack nuget package
        run: dotnet pack --configuration Release WebAppTemplates.csproj
        
      # Publish the nuget package
      - name: Push nuget package
        run: dotnet nuget push --skip-duplicate --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ NUGET_API_KEY }} ./bin/Release/*.nupkg